PROJEKAT_MONGODB/Pages/AddPonuda.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PROJEKAT_MONGODB.Model;
using Microsoft.AspNetCore.Http;
using MongoDB.Driver;
using MongoDB.Bson;

namespace PROJEKAT_MONGODB.Pages
{
    public class AddPonudaModel : PageModel
    {
        [BindProperty]
        public string kruzerID { get; set; }
        [BindProperty]
        public Kruzer kruzer { get; set; }
        [BindProperty]
        public DateTime pocetak { get; set; }
        [BindProperty]
        public DateTime kraj { get; set; }
        [BindProperty]
        public int cena { get; set; }
        private readonly IMongoCollection<Kruzer> _dbKruzeri;
        private readonly IMongoCollection<Ponuda> _dbPonude;
        private readonly IMongoCollection<Korisnik> _dbKorisnici;
        public string Message { get; set; }
        public AddPonudaModel(IDatabaseSettings settings)
        {
            var client = new MongoClient("mongodb://localhost/?safe=true");
            var database = client.GetDatabase("SEVENSEAS");
            _dbKruzeri = database.GetCollection<Kruzer>("kruzeri");
            _dbPonude = database.GetCollection<Ponuda>("ponude");
            _dbKorisnici = database.GetCollection<Korisnik>("korisnici");
        }

        public async Task<IActionResult> OnGet(string kruzerId)
        {
            String email = HttpContext.Session.GetString("Email");
            if (email == null) return RedirectToPage("/Login");
            if (email != null)
            {
                Korisnik k = _dbKorisnici.AsQueryable<Korisnik>().Where(x => x.Email == email).FirstOrDefault();
                if (k.Tip == 1)
                { return RedirectToPage("/Login"); }
                else { Message = "Menadzer"; }
            }

            ObjectId objId = new ObjectId(kruzerId);
            kruzer = await _dbKruzeri.Find(kruzer => kruzer.Id == objId).FirstOrDefaultAsync();
            kruzerID = kruzerId;
            if (kruzer == null) return RedirectToPage("/Index");
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {

            if (pocetak.CompareTo(kraj) > 0 || cena < 1) return Page();
            Ponuda novaPonuda = new Ponuda();
            novaPonuda.Cena = cena;
            novaPonuda.Pocetak = new DateTime(pocetak.Ticks, DateTimeKind.Utc);
            novaPonuda.Kraj = new DateTime(kraj.Ticks, DateTimeKind.Utc);
            novaPonuda.Kruzer = new MongoDBRef("kruzeri", new ObjectId(kruzerID));
            await _dbPonude.InsertOneAsync(novaPonuda);

            var update = Builders<Kruzer>.Update.Push(Hotel => Hotel.Ponude, new MongoDBRef("ponude", novaPonuda.Id));
            await _dbKruzeri.UpdateOneAsync(Hotel => Hotel.Id == new ObjectId(kruzerID), update);
            return RedirectToPage("/KruzerSingle", new { id = kruzerID });
        }
    }
}

PROJEKAT_MONGODB/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using PROJEKAT_MONGODB.Model;
using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization;

namespace PROJEKAT_MONGODB.Pages
{
    public class AdminModel : PageModel
    {
        private readonly IMongoCollection<Kruzer> kr;
        private readonly IMongoCollection<Ponuda> p;
        private readonly IMongoCollection<Korisnik> ko;
        private readonly IMongoCollection<Rezervacija> r;
        private readonly IMongoCollection<Kabina> ka;
        [BindProperty]
        public List<Kruzer> kruzeri { get; set; }
        [BindProperty]
        public List<Korisnik> korisnici { get; set; }
        [BindProperty]
        public List<Rezervacija> rezervacije { get; set; }
        //[BindProperty]
        //public List<Kruzer> kruzeriMenadzera { get; set; }
        [BindProperty]
        public List<Ponuda> ponudeRezervacija { get; set; }
        [BindProperty]
        public List<Kruzer> kruzeriRezervacija { get; set; }
        [BindProperty]
        public List<Korisnik> menadzeriRezervacija { get; set; }
        [BindProperty]
        public List<Korisnik> menadzeri { get; set; }
        [BindProperty]
        public List<Ponuda> ponude { get; set; }
        //[BindProperty]
        //public List<Kruzer> kruzeriPonuda { get; set; }
        public string Message { get; set; }

        public AdminModel(/*IDatabaseSettings settings*/)
        {
            var client = new MongoClient("mongodb://localhost/?safe=true");
            var database = client.GetDatabase("SEVENSEAS");
            kr = database.GetCollection<Kruzer>("kruzeri");
            ka = database.GetCollection<Kabina>("kabine");
            ko = database.GetCollection<Korisnik>("korisnici");
            p = database.GetCollection<Ponuda>("ponude");
            r = database.GetCollection<Rezervacija>("rezervacije");
            //kruzeriMenadzera = new List<Kruzer>();
            menadzeriRezervacija = new List<Korisnik>();
            ponudeRezervacija = new List<Ponuda>();
            kruzeriRezervacija = new List<Kruzer>();
            menadzeri = new List<Korisnik>();
            ponude = new List<Ponuda>();
            //kruzeriPonuda = new List<Kruzer>();
        }

        public void OnGet()
        {
            String email = HttpContext.Session.GetString("Email");
            if (email != null)
            {
                Korisnik korisnik = ko.AsQueryable<Korisnik>().Where(x => x.Email == email).FirstOrDefault();
                if (korisnik.Tip == 0)
                    Message = "Menadzer";
                else Message = "Admin";
            }


            kruzeri = kr.Find(x => true).ToList();
            rezervacije = r.Find(x => true).ToList();
            korisnici = ko.Find(x => x.Tip == 0).ToList();  
            ponude = p.Find(x => true).ToList();
            foreach (Rezervacija rez in rezervacije)
            {
                ponudeRezervacija.Add(p.Find(x => x.Id.Equals(new ObjectId(rez.Ponuda.Id.ToString()))).FirstOrDefault());
                kruzeriRezervacija.Add(kr.Find(x => x.Id.Equals( new ObjectId(rez.Kruzer.Id.ToString()))).FirstOrDefault());
            }
            foreach (Kruzer kruzer in kruzeriRezervacija)
            {
                menadzeriRezervacija.Add(ko.Find(x => x.Kruzer.Id.Equals(kruzer.Id)).FirstOrDefault());
            }
            foreach (Kruzer kruzer in kruzeri)
            {
                //menadzeri.Add(k.Find(x=>x.Hotel.Id.Equals(hot.Id)).FirstOrDefault());
                //string s = k.AsQueryable<Korisnik>().Select(x=>x.Hotel.Id.AsString).FirstOrDefault();
                Korisnik m = ko.AsQueryable<Korisnik>().Where(x => x.Kruzer.Id == kruzer.Id).FirstOrDefault();
                menadzeri.Add(m);

            }
            //foreach (Korisnik kor in menadzeri)
            //{
            //    kruzeriMenadzera.Add(kr.Find(x => x.Id.Equals(new ObjectId(kor.Kruzer.Id.ToString()))).FirstOrDefault());
            //}
            //foreach (Korisnik kor in menadzeri)
            //{
            //    if(kor==null)
            //    {
            //        continue;
            //    }
            //    var kruzer = kr.Find(x => x.Id.Equals(new ObjectId(kor.Kruzer.Id.ToString()))).FirstOrDefault();
            //    if (kruzer != null)
            //    {
            //        kruzeriMenadzera.Add(kruzer);
            //    }
            //}

        }

        public IActionResult OnPostObrisiRez(string id)
        {
            List<Kabina> kabine = ka.Find(x => true).ToList();
            var pull = Builders<Kabina>.Update.PullFilter(x => x.Rezervacije, Builders<MongoDBRef>.Filter.Where(q => q.Id.Equals(new ObjectId(id))));
            foreach (Kabina kabina in kabine)
            {
                var filter = Builders<Kabina>.Filter.Eq("Id", kabina.Id);
                ka.UpdateOne(filter, pull);
            }
            r.DeleteOne<Rezervacija>(x => x.Id.Equals(new ObjectId(id)));
            return RedirectToPage();
        }

        public IActionResult OnPostStatusAktivno(string id)
        {
            var update = Builders<Rezervacija>.Update.Set("Status", "Aktivno");
            var filter = Builders<Rezervacija>.Filter.Eq("Id", new ObjectId(id));
            r.UpdateOne(filter, update);
            return RedirectToPage();
        }

        public IActionResult OnPostObrisiKruzer(string id)
        {
            Kruzer kruzer = kr.Find(x => x.Id.Equals(new ObjectId(id))).FirstOrDefault();
            //brisanje menadzera kruzera
            var filter1 = Builders<Korisnik>.Filter.Eq("Kruzer.Id", new ObjectId(id));
            ko.DeleteOne(filter1);
            //brisanje soba hotela
            foreach (MongoDBRef kabinaRef in kruzer.Kabine.ToList())
            {
                var filter2 = Builders<Kabina>.Filter.Eq("Id", kabinaRef.Id);
                ka.DeleteOne(filter2);
            }
            //brisanje ponuda vezanih za kruzer
            foreach (MongoDBRef ponudaRef in kruzer.Ponude.ToList())
            {
                var filter3 = Builders<Ponuda>.Filter.Eq("Id", ponudaRef.Id);
                p.DeleteOne(filter3);
            }
            //brisanje rezervacija vezanih za taj kruzer
            var filter = Builders<Rezervacija>.Filter.Eq("Kruzer.Id", new ObjectId(id));
            r.DeleteMany(filter);
            //brisanje kruzera
            kr.DeleteOne(x => x.Id.Equals(new ObjectId(id)));

            return RedirectToPage();
        }
    }
}

PROJEKAT_MONGODB/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PROJEKAT_MONGODB.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PROJEKAT_MONGODB/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using MongoDB.Driver;
using PROJEKAT_MONGODB.Model;

namespace PROJEKAT_MONGODB.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        //public IndexModel(ILogger<IndexModel> logger)
        //{
        //    _logger = logger;
        //}

        public List<Kruzer> topRated { get; set; }
        public string Message { get; set; }


        private readonly IMongoCollection<Kruzer> _dbKruzeri;
        private readonly IMongoCollection<Korisnik> _dbKorisnici;
        private readonly IMongoCollection<Drzava> _dbDrzave;


        public IndexModel(IDatabaseSettings settings)
        {
            //var client = new MongoClient(settings.ConnectionString);
            //var database = client.GetDatabase(settings.DatabaseName);
            var client = new MongoClient("mongodb://localhost/?safe=true");
            var database = client.GetDatabase("SEVENSEAS");
            _dbKruzeri = database.GetCollection<Kruzer>("kruzeri");
            _dbKorisnici = database.GetCollection<Korisnik>("korisnici");
            _dbDrzave = database.GetCollection<Drzava>("drzave");
        }

        public void OnGet()
        {
            topRated = _dbKruzeri.AsQueryable<Kruzer>().OrderByDescending(Kruzer => Kruzer.BrojZvezdica).ToList();



            String email = HttpContext.Session.GetString("Email");
            if (email != null)
            {
                Korisnik k = _dbKorisnici.AsQueryable<Korisnik>().Where(x => x.Email == email).FirstOrDefault();
                if (k.Tip == 0)
                    Message = "Menadzer";
                else Message = "Admin";
            }

        }
        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("Email");
            Message = null;
            return RedirectToPage("/Index");
            //<a asp-page="/Index" asp-page-handler="Logout">Logout</a>
        }
    }
}

PROJEKAT_MONGODB/Pages/Kontakt.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using PROJEKAT_MONGODB.Model;
using MongoDB.Driver;

namespace PROJEKAT_MONGODB.Pages
{
    public class KontaktModel : PageModel
    {
        public string Message { get; set; }
        public void OnGet()
        {
            var client = new MongoClient("mongodb://localhost/?safe=true");
            var db = client.GetDatabase("SEVENSEAS");
            var collection = db.GetCollection<Korisnik>("korisnici");

            String email = HttpContext.Session.GetString("Email");
            if (email != null)
            {
                Korisnik k = collection.AsQueryable<Korisnik>().Where(x => x.Email == email).FirstOrDefault();
                if (k.Tip == 0)
                    Message = "Menadzer";
                else Message = "Admin";
            }
        }
    }
}

PROJEKAT_MONGODB/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongoDB.Driver;
using PROJEKAT_MONGODB.Model;
using Microsoft.AspNetCore.Http;
namespace PROJEKAT_MONGODB.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string email { get; set; }
        [BindProperty]
        public string sifra { get; set; }
        public string ErrorMessage { get; set; }
        public string Message { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPostLogin()
        {
            var client = new MongoClient("mongodb://localhost/?safe=true");
            var db = client.GetDatabase("SEVENSEAS");
            var collection = db.GetCollection<Korisnik>("korisnici");

            /*var filter = Builders<BsonDocument>.Filter.And(
                Builders<BsonDocument>.Filter.Eq("email", email),
                Builders<BsonDocument>.Filter.Eq("sifra", sifra)
            );*/

            Korisnik k = collection.AsQueryable<Korisnik>().Where(x => x.Email == email && x.Sifra == sifra).FirstOrDefault();

            if (k != null)
            {
                HttpContext.Session.SetString("Email", email);
                return RedirectToPage("/Index");
            }
            ErrorMessage = "Invalid email address or password!";
            return Page();
        }
    }
}

PROJEKAT_MONGODB/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROJEKAT_MONGODB.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PROJEKAT_MONGODB/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongoDB.Driver;
using PROJEKAT_MONGODB.Model;

namespace PROJEKAT_MONGODB.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public Korisnik NoviKorisnik { get; set; }
        [BindProperty]
        public string ConfrimPassword { get; set; }
        public string ErrorMessage { get; set; }
        public string Message { get; set; }
        public void OnGet()
        {
        }
        public IActionResult OnPostRegister()
        {
            var client = new MongoClient("mongodb://localhost/?safe=true");
            var db = client.GetDatabase("SEVENSEAS");
            var collection = db.GetCollection<Korisnik>("korisnici");

            Korisnik k = collection.AsQueryable<Korisnik>().Where(x => x.Email == NoviKorisnik.Email).FirstOrDefault();
            if (!NoviKorisnik.Sifra.Equals(ConfrimPassword))
            {
                ErrorMessage = "Sifre se ne podudaraju!";
                return Page();
            }
            if (k != null)
            {
                ErrorMessage = "Vec postoji korisnik sa ovom email adresom!";
                return Page();
            }
            NoviKorisnik.Tip = 0;
            collection.InsertOne(NoviKorisnik);
            HttpContext.Session.SetString("Email", NoviKorisnik.Email);
            return RedirectToPage("/AddKruzer");
            //return new JsonResult(NoviKorisnik);
        }
    }
}

PROJEKAT_MONGODB/Pages/Admin.cshtml
@page
@model PROJEKAT_MONGODB.Pages.AdminModel
@{
}
<section class="w3l-content-with-photo-11">
    <div class="contentwithphoto-11 py-5">
        <div class="container py-md-3">
            <div style="margin-bottom:10px;" class="tabelaRez-info">
                <div class="tab">
                    <button class="tablinks" onclick="openTable(event, 'Rezervacije')">Rezervacije</button>
                    <button class="tablinks" onclick="openTable(event, 'Kruzeri')">Kruzeri</button>
                    <button class="tablinks" onclick="openTable(event, 'Korisnici')">Korisnici</button>
                </div>

                <div id="Rezervacije" class="tabcontent">
                    <form method="post" class="rez-tabela">
                        <h4 class="predstojece-rez">Rezervacije</h4>
                        @if (Model.rezervacije.Count == 0)
                        {
                            <label class="nema-rez">Ne postoje rezervacije!</label>
                        }
                        else
                        {
                            <div style="overflow-y:scroll; height:500px;">
                                <table id="offers1" class="table" style="width:95%;">
                                    <thead>
                                        <tr>
                                            <th>Ime Korisnika</th>
                                            <th>Prezime Korisnika</th>
                                            <th>Broj Telefona Korisnika</th>
                                            <th>Datum Rezervacije</th>
                                            <th>Kruzer</th>
                                            <th>Kontakt Telefon Kruzera</th>
                                            <th>Ime Menadzera</th>
                                            <th>Email Menadzera</th>
                                            <th>Broj Telefona Menadzera</th>
                                            <th>Ponuda</th>
                                            <th>Cena U Evrima</th>
                                            <th>Status</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (int i = 0; i < @Model.rezervacije.Count; i++)
                                        {
                                            <tr>
                                                <td>@Model.rezervacije.ElementAt(i).ImeKorisnika</td>
                                                <td>@Model.rezervacije.ElementAt(i).PrezimeKorisnika</td>
                                                <td>@Model.rezervacije.ElementAt(i).BrojTelefonaKorisnika</td>
                                                <td>@Model.rezervacije.ElementAt(i).DatumKreiranja.ToString("dd.MM.yyyy.")</td>
                                                <td><a asp-page="/KruzerSingle" asp-route-id="@Model.kruzeriRezervacija.ElementAt(i).Id">@Model.kruzeriRezervacija.ElementAt(i).Naziv</a></td>
                                                <td>@Model.kruzeriRezervacija.ElementAt(i).KontaktTelefon</td>
                                                <td>@Model.menadzeriRezervacija.ElementAt(i).Ime @Model.menadzeriRezervacija.ElementAt(i).Prezime</td>
                                                <td>@Model.menadzeriRezervacija.ElementAt(i).Email</td>
                                                <td>@Model.menadzeriRezervacija.ElementAt(i).BrojTelefona</td>
                                                <td>@Model.ponudeRezervacija.ElementAt(i).Pocetak.ToString("dd.MM.yyyy.") - @Model.ponudeRezervacija.ElementAt(i).Kraj.ToString("dd.MM.yyyy.")</td>
                                                <td>@Model.ponudeRezervacija.ElementAt(i).Cena</td>
                                                <td>@Model.rezervacije.ElementAt(i).Status</td>
                                                <td><button class="otkaziRez" asp-route-id="@Model.rezervacije.ElementAt(i).Id" asp-page-handler="ObrisiRez" onclick="return confirm('Da li ste sigurni da zelite da obrisete ovu rezervaciju?');">Obrisi</button></td>
                                                @if (Model.rezervacije.ElementAt(i).Status == "Na cekanju!")
                                                {
                                                    <td><button class="otkaziRez" asp-route-id="@Model.rezervacije.ElementAt(i).Id" asp-page-handler="StatusAktivno" onclick="return confirm('Da li ste sigurni da zelite da promenite status na Aktivno?');">Aktivno</button></td>
}
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        }
                    </form>
                </div>

                <div id="Kruzeri" class="tabcontent">
                    <form method="post" class="rez-tabela">
                        <h4 class="predstojece-rez">Kruzeri koji imaju rezervacije</h4>
                        @*@if (Model.kruzeri.Count == 0)
                        {
                            <label class="nema-rez">Ne postoje kruzeri!</label>
                        }
                        else
                        {*@
                            <div style="overflow-y:scroll; height:500px;">
                                <table id="offers1" class="table" style="width:95%;">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Naziv</th>
                                            <th>Kontakt Telefon Kruzera</th>
                                            <th>Ime menadzera</th>
                                            <th>Email Menadzera</th>
                                            <th>Kontakt Telefon Menadzera</th>
                                            <th>Drzave</th>
                                            <th>Gradovi</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (int i = 0; i < @Model.ponudeRezervacija.Count; i++)
                                        {
                                           
                                        <tr>
                                            <td><a asp-page="/KruzerSingle" asp-route-id="@Model.kruzeri.ElementAt(i).Id"><img src="@Model.kruzeri.ElementAt(i).GlavnaSlika" style="width:150px; height:90px;"></a></td>
                                            <td>@Model.kruzeri.ElementAt(i).Naziv</td>
                                            <td>@Model.kruzeriRezervacija.ElementAt(i).KontaktTelefon</td>
                                            
                                            <td>@Model.menadzeri.ElementAt(i).Ime @Model.menadzeri.ElementAt(i).Prezime</td>
                                            <td>@Model.menadzeri.ElementAt(i).Email</td>
                                            <td>@Model.menadzeri.ElementAt(i).BrojTelefona</td>
                                            
                                            <td>
                                                @foreach (var d1 in Model.kruzeri.ElementAt(i).Drzave)
                                                {

                                                    @d1.Naziv<bold> </bold>
                                                } 
                                                </td>
                
                                            <td> @foreach (var g1 in Model.kruzeri.ElementAt(i).Gradovi)
                                            {
                                                 <bold> </bold>    @g1.Naziv 
                                            }</td>
                
                                            <td><button class="otkaziRez" asp-route-id="@Model.kruzeri.ElementAt(i).Id" asp-page-handler="ObrisiKruzer" onclick="return confirm('Da li ste sigurni da zelite da obrisete ovaj kruzer?(Brise se i korisnik ciji je ovo kruzer)');">Obrisi</button></td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        
                    </form>
                </div>

                <div id="Korisnici" class="tabcontent">
                    <form method="post" class="rez-tabela">
                        <h4 class="predstojece-rez">Korisnici</h4>
                        @*@if (Model.korisnici.Count == 0)
                        {
                            <label class="nema-rez">Ne postoje korisnici!</label>
                        }
                        else
                        {*@
                            <div style="overflow-y:scroll; height:500px;">
                                <table id="offers" class="table" style="width:95%;">
                                    <thead>
                                        <tr>
                                            <th>Ime i Prezime</th>
                                            <th>Email</th>
                                            <th>Broj Telefona</th>
                                            @*<th>Kontakt Telefon</th>*@
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (int i = 0; i < @Model.menadzeri.Count; i++)
                                        {
                                            <tr>
                                                <td>@Model.menadzeri.ElementAt(i).Ime @Model.menadzeri.ElementAt(i).Prezime</td>
                                           
                                                <td>@Model.menadzeri.ElementAt(i).Email</td>
                                                <td>@Model.menadzeri.ElementAt(i).BrojTelefona</td>
                                               
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    function openTable(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

PROJEKAT_MONGODB/Pages/Login.cshtml
@page
@model PROJEKAT_MONGODB.Pages.LoginModel
@{
}
<section class="w3l-login">
    <div class="login-bg section-gap">
        <div class="container">
            <!---728x90--->


            <div class="login-form">
                <h4 class="form-head">Dobrodosli, molimo Vas prijavite se</h4>
                <form method="post">
                    <div class="">
                        <p class="text-head">Email</p>
                        <input type="text" required="" asp-for="email" placeholder="Please Enter Email.." class="input" />
                    </div>
                    <div class="">
                        <p class="text-head">Sifra</p>
                        <input type="password" required="" asp-for="sifra" placeholder="Please Enter Password.." class="input" />

                    </div>
                    <span class="error">@Model.ErrorMessage</span>
                    
                    <div class="d-grid align-login-register">
                        <button type="submit" class="btn btn-theme4"style="background-color:darkturquoise" asp-page-handler="Login">Prijavi se</button>
                        <a asp-page="/Register" class="signuplink" style="display:contents">Nemate nalog? Kreirajte nalog</a>
                    </div>
                </form>

            </div>
        </div>
        <!---728x90--->

    </div>

</section>

PROJEKAT_MONGODB/Pages/ONama.cshtml
@page
@model PROJEKAT_MONGODB.Pages.ONamaModel
@{
}
<section class="w3l-content-1" id="about">
    <div id="content1-block" class="py-5">
        <div class="container py-md-3">
            <div class="heading text-center mx-auto">
                <h3 class="head">Naša ideja</h3>
                <p class="my-3 head">
                     U moru ponuda za putovanja kruzerima, kao putnik, veoma je teško sagledati sve neophodne aspekte i informacije vezane za samo putovanje, odabir destinacija, i slicno , a pri tom izbeći moguće neprijatnosti i odmor provesti sa potpunim uživanjem.
                    Upravo u toj činjenici leži naša ideja da se putnik do najsitnijih detalja informiše o željenoj destinaciji, da se pruži prava i proverena informacija, i da se odabere pravi kruzer koji ce ispuniti sva putnikova ocekivanja.                                                          
               
                </p>
            </div>
            <div class="cwp23-img mt-5">
                <img src="assets/images/banner-1.jpg" class="img-responsive" alt="">
            </div>
           
        </div>
    </div>
</section>